export const ChargeReason = {
  BASE_FARE: 'BASE_FARE',
  FREE_TRANSFER_WITHIN_90_MINUTES: 'FREE_TRANSFER_WITHIN_90_MINUTES',
  METRO_TO_MGT_FREE_TRANSFER: 'METRO_TO_MGT_FREE_TRANSFER',
  MGT_TO_METRO_FREE_TRANSFER: 'MGT_TO_METRO_FREE_TRANSFER',
  METRO_TO_MCK_FREE_TRANSFER: 'METRO_TO_MCK_FREE_TRANSFER',
  MCK_TO_METRO_FREE_TRANSFER: 'MCK_TO_METRO_FREE_TRANSFER',
  MCD_ENTRY_INCLUDED_IN_WINDOW: 'MCD_ENTRY_INCLUDED_IN_WINDOW',
  MCD_EXIT_COMPLETION: 'MCD_EXIT_COMPLETION',
  MCD_ENTRY_COMPLETION: 'MCD_ENTRY_COMPLETION',
  MCD_PAIR_AUTO_COMPLETED_BY_CARRIER: 'MCD_PAIR_AUTO_COMPLETED_BY_CARRIER',
  MCD_PAIR_AUTO_COMPLETED_BY_FARE_CORE: 'MCD_PAIR_AUTO_COMPLETED_BY_FARE_CORE',
  MOSCOW_TO_REGION_EXIT_SURCHARGE: 'MOSCOW_TO_REGION_EXIT_SURCHARGE',
  REGION_TO_MOSCOW_FREE_METRO_TRANSFER: 'REGION_TO_MOSCOW_FREE_METRO_TRANSFER',
  SAME_CARRIER_NEW_WINDOW: 'SAME_CARRIER_NEW_WINDOW',
  WINDOW_EXPIRED: 'WINDOW_EXPIRED',
  TRANSPORT_DAY_BOUNDARY: 'TRANSPORT_DAY_BOUNDARY',
  DUPLICATED_LINK_NEW_WINDOW: 'DUPLICATED_LINK_NEW_WINDOW',
  UNSUPPORTED_CPPK_TRAIN_SURCHARGE_7000: 'UNSUPPORTED_CPPK_TRAIN_SURCHARGE_7000'
} as const

export type ChargeReasonType = (typeof ChargeReason)[keyof typeof ChargeReason]
