export const WarningCode = {
  DECLINED_VALIDATION_IGNORED: 'DECLINED_VALIDATION_IGNORED',
  DUPLICATE_VALIDATION_IGNORED: 'DUPLICATE_VALIDATION_IGNORED',
  EVENT_OUTSIDE_REQUEST_TRANSPORT_DATE: 'EVENT_OUTSIDE_REQUEST_TRANSPORT_DATE',
  MCD_PAIR_AUTO_COMPLETED: 'MCD_PAIR_AUTO_COMPLETED',
  MCD_PAIR_BROKE_TRANSFER_CHAIN: 'MCD_PAIR_BROKE_TRANSFER_CHAIN',
  UNSUPPORTED_CPPK_TRAIN_SURCHARGE_7000: 'UNSUPPORTED_CPPK_TRAIN_SURCHARGE_7000',
  DP_VALIDATION_TYPE_FILTERED_OR_UNSUPPORTED: 'DP_VALIDATION_TYPE_FILTERED_OR_UNSUPPORTED',
  TRANSPORT_DAY_BOUNDARY_SPLIT: 'TRANSPORT_DAY_BOUNDARY_SPLIT',
  DUPLICATED_LINK_STARTED_NEW_WINDOW: 'DUPLICATED_LINK_STARTED_NEW_WINDOW',
  CPPK_VALIDATION_TYPE_IGNORED_FOR_NON_CPPK_CARRIER:
    'CPPK_VALIDATION_TYPE_IGNORED_FOR_NON_CPPK_CARRIER'
} as const

export type WarningCodeType = (typeof WarningCode)[keyof typeof WarningCode]
